version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1-node-browsers
    steps:
      - checkout

      # Install our deps
      - run:
          name: Install deps
          command: |
            npm install
            sudo npm install -g karma-cli

      # TODO: cache the node-modules directory, but how to detect new versions???

      # We want to share the results of "lein deps" between runs.
      # We assume that the maven cache can change only if "project.clj"
      # changes (see the checksum in the name of the key below).
      - restore_cache:
          keys:
          - m2-{{ checksum "project.clj" }}

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "project.clj" }}

      # For better visibility in the build summary page, we use a separate
      # run step per test file. In this case, we don't want to stop the build
      # on first failure, so we use the `when` keyword.

      - run:
          name: Testing Clojure build
          when: on_success # This is the first test
          command: lein test ghostwheel.dev-test

      - run:
          name: Testing ClojureScript build (chrome-headless, dev environment)
          when: always
          command: lein doo chrome-headless dev-test once

      - run: 
          name: Testing ClojureScript build (chrome-headless, prod environment)
          when: always
          command: lein doo chrome-headless prod-test once

      - run:
          name: Testing ClojureScript build (node, dev environment)
          when: always
          command: lein doo node dev-test-node once

      - run:
          name: Testing ClojureScript build (node, prod environment)
          when: always
          command: lein doo node prod-test-node once
